//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptology
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int CId { get; set; }
        public string Cname { get; set; }
        public decimal Price_usd { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> Rank { get; set; }
        public decimal Price_btc { get; set; }
        public Nullable<decimal> C24h_volume_usd { get; set; }
        public decimal Market_cap_usd { get; set; }
        public Nullable<decimal> Available_supply { get; set; }
        public Nullable<decimal> Max_supply { get; set; }
        public Nullable<decimal> Percent_change_7d { get; set; }
        public string Last_updated { get; set; }
    }
}
